# Generated by Django 4.2.30 on 2026-05-22 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('icono', models.CharField(default='📁', max_length=10, verbose_name='Icono')),
            ],
            options={
                'verbose_name': 'Contexto',
                'verbose_name_plural': 'Contextos',
            },
        ),
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('nivel', models.IntegerField(default=0, verbose_name='Nivel')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('contexto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_arbol.contexto', verbose_name='Contexto')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='app_arbol.nodo', verbose_name='Padre')),
            ],
            options={
                'verbose_name': 'Nodo',
                'verbose_name_plural': 'Nodos',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
